### PR TITLE
 Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by bobbypiper**

### CODE REVIEW

**Comment by ivanvasechko** [comment]
@dusterio hey, is there a chance we could get it merged, please?

**Comment by midnite81** [comment]
+1 for this, would be super helpful if you are able @dusterio

**Comment by AntonCooper** [comment]
+1 a release for this would be super useful!

**Comment by alexw23** [comment]
@dusterio any chance this can be merged, such a simple one :)

**Comment by Nilanth** [comment]
+1 a release for this would be super useful!

**Review by EduardMartiVaquer — APPROVED** [review]

**Comment by pekral** [comment]
Is it possible to merge these changes in the near future?

**Comment by svet-penev** [comment]
@dusterio 
+1 for this one, is there a changes to merge it ?

**Review by ivanvasechko — APPROVED** [review]

**Comment by pekral** [comment]
Any progress in this issue?

**Comment by alexw23** [comment]
image

**Comment by clevrdavid** [comment]
image

**Comment by alexw23** [comment]
images (1)

**Pull request merged**
